
declare
      num number;
begin
    select count(1) into num from user_tables where table_name = upper('OMS_ORDER_PUSH_KAFKA') ;
    if num > 0 then
        execute immediate 'drop table OMS_ORDER_PUSH_KAFKA' ;
    end if;
end;
/

CREATE TABLE XHWL_OMS.OMS_ORDER_PUSH_KAFKA (
    UUID NVARCHAR2(36) VISIBLE NOT NULL PRIMARY KEY,
    CREATED_BY NVARCHAR2(36) VISIBLE ,
    CREATED_TIME DATE VISIBLE ,
    UPDATED_BY NVARCHAR2(36) VISIBLE ,
    UPDATED_TIME DATE VISIBLE ,
    VERSION_CODE NVARCHAR2(36) VISIBLE ,
    ITEM1 NVARCHAR2(100) VISIBLE ,
    ITEM2 NVARCHAR2(100) VISIBLE ,
    ITEM3 NVARCHAR2(100) VISIBLE ,
    ITEM4 NVARCHAR2(100) VISIBLE
);

-- 表注释
COMMENT ON TABLE XHWL_OMS.OMS_ORDER_PUSH_KAFKA IS 'OMS订单系统-内部订单下发记录';

-- 主键
COMMENT ON COLUMN XHWL_OMS.OMS_ORDER_PUSH_KAFKA.UUID IS '主键ID，下发KAFKA 使用的EventId';
-- 必须的9个字段
COMMENT ON COLUMN XHWL_OMS.OMS_ORDER_PUSH_KAFKA.CREATED_BY IS '创建人';
COMMENT ON COLUMN XHWL_OMS.OMS_ORDER_PUSH_KAFKA.CREATED_TIME IS '创建时间';
COMMENT ON COLUMN XHWL_OMS.OMS_ORDER_PUSH_KAFKA.UPDATED_BY IS '更新人';
COMMENT ON COLUMN XHWL_OMS.OMS_ORDER_PUSH_KAFKA.UPDATED_TIME IS '更新时间';
COMMENT ON COLUMN XHWL_OMS.OMS_ORDER_PUSH_KAFKA.VERSION_CODE IS '版本号';
COMMENT ON COLUMN XHWL_OMS.OMS_ORDER_PUSH_KAFKA.ITEM1 IS '预留字段';
COMMENT ON COLUMN XHWL_OMS.OMS_ORDER_PUSH_KAFKA.ITEM2 IS '预留字段';
COMMENT ON COLUMN XHWL_OMS.OMS_ORDER_PUSH_KAFKA.ITEM3 IS '预留字段';
COMMENT ON COLUMN XHWL_OMS.OMS_ORDER_PUSH_KAFKA.ITEM4 IS '预留字段';

-- 添加扩展字段
alter table XHWL_OMS.OMS_ORDER_PUSH_KAFKA add TOPIC NVARCHAR2(100);
comment on column XHWL_OMS.OMS_ORDER_PUSH_KAFKA.TOPIC is '下发KAFKA 的主题';

alter table XHWL_OMS.OMS_ORDER_PUSH_KAFKA add EVENT_TYPE NVARCHAR2(100);
comment on column XHWL_OMS.OMS_ORDER_PUSH_KAFKA.EVENT_TYPE is '下发KAFKA 的事件类型常量字符串';

alter table XHWL_OMS.OMS_ORDER_PUSH_KAFKA add RF_ORDER_ID_INNER NVARCHAR2(36);
comment on column XHWL_OMS.OMS_ORDER_PUSH_KAFKA.RF_ORDER_ID_INNER is '内部订单号';

alter table XHWL_OMS.OMS_ORDER_PUSH_KAFKA add PUSH_DATE DATE;
comment on column XHWL_OMS.OMS_ORDER_PUSH_KAFKA.PUSH_DATE is '下发时间，未下发时置NULL，下发时填具体下发时间';

alter table XHWL_OMS.OMS_ORDER_PUSH_KAFKA add RF_PROCESSING_TYPE NVARCHAR2(3);
comment on column XHWL_OMS.OMS_ORDER_PUSH_KAFKA.RF_PROCESSING_TYPE is
    '订单处理类型枚举(ProcessingTypeEnum)【select:10-入库,20-出库,30-库内处理,40-运输,50-入库+运输,60-出库+运输,70-计划,80-入库+出库】';


