package com.suyh.version03.mapper;

import com.suyh.version03.model.CrmCustomerInfo;
import java.util.List;

public interface CrmCustomerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_CUSTOMER_INFO
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    int deleteByPrimaryKey(String customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_CUSTOMER_INFO
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    int insert(CrmCustomerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_CUSTOMER_INFO
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    CrmCustomerInfo selectByPrimaryKey(String customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_CUSTOMER_INFO
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    List<CrmCustomerInfo> selectAll();
}