package com.suyh.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Table: crm_customer_info
 *   客户基本信息表结构：内部客户、供应商、承运商
 *
 * @author su.yunhong
 */
public class CrmCustomerInfo implements Serializable {
    /**
     * Column: customer_id
     *   主键：客户ID
     */
    private String customerId;

    /**
     * Column: full_name
     *   客户全称
     */
    private String fullName;

    /**
     * Column: short_name
     *   客户简称
     */
    private String shortName;

    /**
     * Column: manager_name
     *   负责人
     */
    private String managerName;

    /**
     * Column: manager_phone
     *   联系电话
     */
    private String managerPhone;

    /**
     * Column: inner_customer
     *   是否内部用户(这个字段似乎有些多余了)【radio:1-是,2-否】
     */
    private String innerCustomer;

    /**
     * Column: customer_type
     *   客户类型【select:1-内部客户,2-供应商,3-承运商】
     */
    private String customerType;

    /**
     * Column: address
     *   联系地址
     */
    private String address;

    /**
     * Column: us_plat_system
     *   是否使用平台系统(当有自有系统时则可不使用平台系统)【radio:1-是,2-否】
     */
    private String usPlatSystem;

    /**
     * Column: platform_admin_user
     *   平台管理员帐号，非自有系统用户才会有。
     */
    private String platformAdminUser;

    /**
     * Column: created_date
     *   创建时间
     */
    private Date createdDate;

    /**
     * Column: settle_day
     *   月结日，以0 表示自然月
     */
    private Integer settleDay;

    /**
     * Column: price
     *   价格，10 位长度，两位小数位
     */
    private BigDecimal price;

    /**
     * Column: using_status
     *   启用状态【radio:1-是(启用),2-否(停用)】
     */
    private Long usingStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crm_customer_info
     *
     * @author su.yunhong
     */
    private static final long serialVersionUID = 1L;

    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    public String getShortName() {
        return shortName;
    }

    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    public String getManagerName() {
        return managerName;
    }

    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    public String getManagerPhone() {
        return managerPhone;
    }

    public void setManagerPhone(String managerPhone) {
        this.managerPhone = managerPhone == null ? null : managerPhone.trim();
    }

    public String getInnerCustomer() {
        return innerCustomer;
    }

    public void setInnerCustomer(String innerCustomer) {
        this.innerCustomer = innerCustomer == null ? null : innerCustomer.trim();
    }

    public String getCustomerType() {
        return customerType;
    }

    public void setCustomerType(String customerType) {
        this.customerType = customerType == null ? null : customerType.trim();
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    public String getUsPlatSystem() {
        return usPlatSystem;
    }

    public void setUsPlatSystem(String usPlatSystem) {
        this.usPlatSystem = usPlatSystem == null ? null : usPlatSystem.trim();
    }

    public String getPlatformAdminUser() {
        return platformAdminUser;
    }

    public void setPlatformAdminUser(String platformAdminUser) {
        this.platformAdminUser = platformAdminUser == null ? null : platformAdminUser.trim();
    }

    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Integer getSettleDay() {
        return settleDay;
    }

    public void setSettleDay(Integer settleDay) {
        this.settleDay = settleDay;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public Long getUsingStatus() {
        return usingStatus;
    }

    public void setUsingStatus(Long usingStatus) {
        this.usingStatus = usingStatus;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", customerId=").append(customerId);
        sb.append(", fullName=").append(fullName);
        sb.append(", shortName=").append(shortName);
        sb.append(", managerName=").append(managerName);
        sb.append(", managerPhone=").append(managerPhone);
        sb.append(", innerCustomer=").append(innerCustomer);
        sb.append(", customerType=").append(customerType);
        sb.append(", address=").append(address);
        sb.append(", usPlatSystem=").append(usPlatSystem);
        sb.append(", platformAdminUser=").append(platformAdminUser);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", settleDay=").append(settleDay);
        sb.append(", price=").append(price);
        sb.append(", usingStatus=").append(usingStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}