package com.suyh.version03.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 客户基本信息表结构：内部客户、供应商、承运商
 * 
 * @table: CRM_CUSTOMER_INFO
 * @author: suyh
 * @date: 2020-05-02 11:31:57
 */
@ApiModel(value = "客户基本信息表结构：内部客户、供应商、承运商")
public class CrmCustomerInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRM_CUSTOMER_INFO.CUSTOMER_ID
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    @ApiModelProperty(value = "主键：客户ID")
    private String customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRM_CUSTOMER_INFO.FULL_NAME
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    @ApiModelProperty(value = "客户全称")
    private String fullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRM_CUSTOMER_INFO.SHORT_NAME
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    @ApiModelProperty(value = "客户简称")
    private String shortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRM_CUSTOMER_INFO.MANAGER_NAME
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    @ApiModelProperty(value = "负责人")
    private String managerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRM_CUSTOMER_INFO.MANAGER_PHONE
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    @ApiModelProperty(value = "联系电话")
    private String managerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRM_CUSTOMER_INFO.INNER_CUSTOMER
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    @ApiModelProperty(value = "是否内部用户【radio:Y/N】")
    private String innerCustomer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRM_CUSTOMER_INFO.CUSTOMER_TYPE
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    @ApiModelProperty(value = "客户类型【select:1-内部客户,2-供应商,3-承运商】")
    private String customerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRM_CUSTOMER_INFO.ADDRESS
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    @ApiModelProperty(value = "联系地址")
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRM_CUSTOMER_INFO.US_PLAT_SYSTEM
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    @ApiModelProperty(value = "是否使用平台系统【radio:1-是,2-否】")
    private String usPlatSystem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRM_CUSTOMER_INFO.PLATFORM_ADMIN_USER
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    @ApiModelProperty(value = "平台管理员帐号，非自有系统用户才会有。")
    private String platformAdminUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRM_CUSTOMER_INFO.CREATED_DATE
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    @ApiModelProperty(value = "创建时间【格式：yyyy-MM-dd】")
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRM_CUSTOMER_INFO.SETTLE_DAY
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    @ApiModelProperty(value = "月结日，以0 表示自然月")
    private BigDecimal settleDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRM_CUSTOMER_INFO.PRICE
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    @ApiModelProperty(value = "价格，10 位长度，两位小数位")
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CRM_CUSTOMER_INFO.USING_STATUS
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    @ApiModelProperty(value = "启用状态【radio:1-是(启用),2-否(停用)】")
    private BigDecimal usingStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CRM_CUSTOMER_INFO
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_CUSTOMER_INFO.CUSTOMER_ID
     *
     * @return the value of CRM_CUSTOMER_INFO.CUSTOMER_ID
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_CUSTOMER_INFO.CUSTOMER_ID
     *
     * @param customerId the value for CRM_CUSTOMER_INFO.CUSTOMER_ID
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_CUSTOMER_INFO.FULL_NAME
     *
     * @return the value of CRM_CUSTOMER_INFO.FULL_NAME
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_CUSTOMER_INFO.FULL_NAME
     *
     * @param fullName the value for CRM_CUSTOMER_INFO.FULL_NAME
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_CUSTOMER_INFO.SHORT_NAME
     *
     * @return the value of CRM_CUSTOMER_INFO.SHORT_NAME
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_CUSTOMER_INFO.SHORT_NAME
     *
     * @param shortName the value for CRM_CUSTOMER_INFO.SHORT_NAME
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_CUSTOMER_INFO.MANAGER_NAME
     *
     * @return the value of CRM_CUSTOMER_INFO.MANAGER_NAME
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_CUSTOMER_INFO.MANAGER_NAME
     *
     * @param managerName the value for CRM_CUSTOMER_INFO.MANAGER_NAME
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_CUSTOMER_INFO.MANAGER_PHONE
     *
     * @return the value of CRM_CUSTOMER_INFO.MANAGER_PHONE
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public String getManagerPhone() {
        return managerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_CUSTOMER_INFO.MANAGER_PHONE
     *
     * @param managerPhone the value for CRM_CUSTOMER_INFO.MANAGER_PHONE
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public void setManagerPhone(String managerPhone) {
        this.managerPhone = managerPhone == null ? null : managerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_CUSTOMER_INFO.INNER_CUSTOMER
     *
     * @return the value of CRM_CUSTOMER_INFO.INNER_CUSTOMER
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public String getInnerCustomer() {
        return innerCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_CUSTOMER_INFO.INNER_CUSTOMER
     *
     * @param innerCustomer the value for CRM_CUSTOMER_INFO.INNER_CUSTOMER
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public void setInnerCustomer(String innerCustomer) {
        this.innerCustomer = innerCustomer == null ? null : innerCustomer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_CUSTOMER_INFO.CUSTOMER_TYPE
     *
     * @return the value of CRM_CUSTOMER_INFO.CUSTOMER_TYPE
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_CUSTOMER_INFO.CUSTOMER_TYPE
     *
     * @param customerType the value for CRM_CUSTOMER_INFO.CUSTOMER_TYPE
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public void setCustomerType(String customerType) {
        this.customerType = customerType == null ? null : customerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_CUSTOMER_INFO.ADDRESS
     *
     * @return the value of CRM_CUSTOMER_INFO.ADDRESS
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_CUSTOMER_INFO.ADDRESS
     *
     * @param address the value for CRM_CUSTOMER_INFO.ADDRESS
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_CUSTOMER_INFO.US_PLAT_SYSTEM
     *
     * @return the value of CRM_CUSTOMER_INFO.US_PLAT_SYSTEM
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public String getUsPlatSystem() {
        return usPlatSystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_CUSTOMER_INFO.US_PLAT_SYSTEM
     *
     * @param usPlatSystem the value for CRM_CUSTOMER_INFO.US_PLAT_SYSTEM
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public void setUsPlatSystem(String usPlatSystem) {
        this.usPlatSystem = usPlatSystem == null ? null : usPlatSystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_CUSTOMER_INFO.PLATFORM_ADMIN_USER
     *
     * @return the value of CRM_CUSTOMER_INFO.PLATFORM_ADMIN_USER
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public String getPlatformAdminUser() {
        return platformAdminUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_CUSTOMER_INFO.PLATFORM_ADMIN_USER
     *
     * @param platformAdminUser the value for CRM_CUSTOMER_INFO.PLATFORM_ADMIN_USER
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public void setPlatformAdminUser(String platformAdminUser) {
        this.platformAdminUser = platformAdminUser == null ? null : platformAdminUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_CUSTOMER_INFO.CREATED_DATE
     *
     * @return the value of CRM_CUSTOMER_INFO.CREATED_DATE
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_CUSTOMER_INFO.CREATED_DATE
     *
     * @param createdDate the value for CRM_CUSTOMER_INFO.CREATED_DATE
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_CUSTOMER_INFO.SETTLE_DAY
     *
     * @return the value of CRM_CUSTOMER_INFO.SETTLE_DAY
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public BigDecimal getSettleDay() {
        return settleDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_CUSTOMER_INFO.SETTLE_DAY
     *
     * @param settleDay the value for CRM_CUSTOMER_INFO.SETTLE_DAY
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public void setSettleDay(BigDecimal settleDay) {
        this.settleDay = settleDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_CUSTOMER_INFO.PRICE
     *
     * @return the value of CRM_CUSTOMER_INFO.PRICE
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_CUSTOMER_INFO.PRICE
     *
     * @param price the value for CRM_CUSTOMER_INFO.PRICE
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CRM_CUSTOMER_INFO.USING_STATUS
     *
     * @return the value of CRM_CUSTOMER_INFO.USING_STATUS
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public BigDecimal getUsingStatus() {
        return usingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CRM_CUSTOMER_INFO.USING_STATUS
     *
     * @param usingStatus the value for CRM_CUSTOMER_INFO.USING_STATUS
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    public void setUsingStatus(BigDecimal usingStatus) {
        this.usingStatus = usingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CRM_CUSTOMER_INFO
     *
     * @mbg.generated Sat May 02 11:31:57 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", customerId=").append(customerId);
        sb.append(", fullName=").append(fullName);
        sb.append(", shortName=").append(shortName);
        sb.append(", managerName=").append(managerName);
        sb.append(", managerPhone=").append(managerPhone);
        sb.append(", innerCustomer=").append(innerCustomer);
        sb.append(", customerType=").append(customerType);
        sb.append(", address=").append(address);
        sb.append(", usPlatSystem=").append(usPlatSystem);
        sb.append(", platformAdminUser=").append(platformAdminUser);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", settleDay=").append(settleDay);
        sb.append(", price=").append(price);
        sb.append(", usingStatus=").append(usingStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}